name: deepflappy
channels:
  - defaults
dependencies:
  - black
  - fs
  - invoke
  - ipykernel
  - ipython
  - jupyter
  - jupyterlab
  - keras
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pip
  - pyjanitor
  - pylint
  - pyprojroot
  - python-dotenv
  - python=3.11
  - pytorch
  - scipy
  - seaborn
  - tensorflow
  - ydata-profiling
